/**
 * Project gallery data — generated from real Trademark Flooring project photos.
 * Optimized images live in /public/images/gallery/<slug>/.
 */

export type ProjectImage = {
  src?: string;
  alt: string;
  orientation?: "landscape" | "portrait" | "square";
};

export type ProjectSector =
  | "Residential"
  | "Commercial"
  | "High-Rise"
  | "Low-Rise"
  | "Multi-Family";

export type Project = {
  slug: string;
  title: string;
  location: string;
  sector: ProjectSector;
  /** Service tags shown as badges + used for filtering. */
  services: string[];
  year?: number;
  summary: string;
  description: string;
  coverAlt: string;
  images: ProjectImage[];
  featured?: boolean;
};

export const projectSectors: ProjectSector[] = [
  "Residential",
  "Commercial",
  "High-Rise",
  "Low-Rise",
  "Multi-Family",
];

/** Service categories used for gallery filtering. */
export const galleryServices = [
  "Self-Levelling",
  "Hardwood",
  "Laminate",
  "Vinyl",
  "Carpet",
  "Stairs",
] as const;

export const projects: Project[] = [
  {
    slug: "carpet-downtown-vancouver-highrise",
    title: "Carpet Installation — Downtown Vancouver High-Rise",
    location: "Vancouver",
    sector: "High-Rise",
    services: ["Carpet"],
    summary: "Broadloom carpet install in a downtown Vancouver high-rise suite.",
    description: "Comfortable, quiet broadloom carpet installed in a downtown Vancouver high-rise. Trademark Flooring handles condo and tower carpet projects across Vancouver and the Lower Mainland.",
    coverAlt: "Broadloom carpet installed in a downtown Vancouver high-rise suite",
    images: [
    { src: "/images/gallery/carpet-downtown-vancouver-highrise/carpet-downtown-vancouver-highrise-1.jpg", alt: "Broadloom carpet installed in a downtown Vancouver high-rise suite", orientation: "portrait" },
    ],
  },
  {
    slug: "carpet-tile-burnaby-showroom",
    title: "Carpet Tile — Burnaby Showroom",
    location: "Burnaby",
    sector: "Commercial",
    services: ["Carpet"],
    summary: "Commercial carpet tile installed in a Burnaby showroom.",
    description: "Modular carpet tile installed in a Burnaby retail showroom for a durable, easily maintained commercial floor. Trademark Flooring serves showrooms and offices across Burnaby and Metro Vancouver.",
    coverAlt: "Commercial carpet tile installed in a Burnaby showroom",
    images: [
    { src: "/images/gallery/carpet-tile-burnaby-showroom/carpet-tile-burnaby-showroom-1.jpg", alt: "Commercial carpet tile installed in a Burnaby showroom", orientation: "portrait" },
    { src: "/images/gallery/carpet-tile-burnaby-showroom/carpet-tile-burnaby-showroom-2.jpg", alt: "Commercial carpet tile installed in a Burnaby showroom", orientation: "portrait" },
    ],
  },
  {
    slug: "commercial-carpet-vancouver-renfrew-corridor",
    title: "Commercial Corridor Carpet — Renfrew, Vancouver",
    location: "Vancouver",
    sector: "Commercial",
    services: ["Carpet"],
    summary: "Hard-wearing corridor carpet for a Renfrew, Vancouver building.",
    description: "Heavy-traffic corridor carpet installed for a building in the Renfrew area of Vancouver. Trademark Flooring installs commercial and multi-family corridor carpet throughout Vancouver.",
    coverAlt: "Commercial corridor carpet in a Renfrew, Vancouver building",
    images: [
    { src: "/images/gallery/commercial-carpet-vancouver-renfrew-corridor/commercial-carpet-vancouver-renfrew-corridor-1.jpg", alt: "Commercial corridor carpet in a Renfrew, Vancouver building", orientation: "portrait" },
    { src: "/images/gallery/commercial-carpet-vancouver-renfrew-corridor/commercial-carpet-vancouver-renfrew-corridor-2.jpg", alt: "Commercial corridor carpet in a Renfrew, Vancouver building", orientation: "portrait" },
    { src: "/images/gallery/commercial-carpet-vancouver-renfrew-corridor/commercial-carpet-vancouver-renfrew-corridor-3.jpg", alt: "Commercial corridor carpet in a Renfrew, Vancouver building", orientation: "portrait" },
    { src: "/images/gallery/commercial-carpet-vancouver-renfrew-corridor/commercial-carpet-vancouver-renfrew-corridor-4.jpg", alt: "Commercial corridor carpet in a Renfrew, Vancouver building", orientation: "portrait" },
    ],
  },
  {
    slug: "acacia-prefinished-hardwood-vancouver",
    title: "Acacia Prefinished Hardwood Flooring",
    location: "Metro Vancouver",
    sector: "Residential",
    services: ["Hardwood"],
    featured: true,
    summary: "Rich acacia prefinished hardwood installed in a Metro Vancouver home.",
    description: "Warm, character-rich acacia prefinished hardwood installed throughout a Metro Vancouver home. Trademark Flooring supplies and installs prefinished and site-finished hardwood across the Lower Mainland.",
    coverAlt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home",
    images: [
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-1.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-2.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-3.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-4.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-5.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-6.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-7.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-8.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-9.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-10.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-11.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-12.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-13.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-14.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-15.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-16.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-17.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-18.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/acacia-prefinished-hardwood-vancouver/acacia-prefinished-hardwood-vancouver-19.jpg", alt: "Acacia prefinished hardwood flooring installed in a Metro Vancouver home", orientation: "portrait" },
    ],
  },
  {
    slug: "hardwood-flooring-new-westminster-house",
    title: "Hardwood Flooring — New Westminster Home",
    location: "New Westminster",
    sector: "Residential",
    services: ["Hardwood"],
    featured: true,
    summary: "Solid hardwood flooring installed in a New Westminster house.",
    description: "Solid hardwood flooring supplied and installed in a New Westminster character home. Trademark Flooring restores and installs hardwood in homes across New Westminster and the Lower Mainland.",
    coverAlt: "Solid hardwood flooring installed in a New Westminster home",
    images: [
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-1.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-2.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "landscape" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-3.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-4.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "landscape" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-5.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-6.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-7.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-8.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-9.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-10.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-11.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-12.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "landscape" },
    { src: "/images/gallery/hardwood-flooring-new-westminster-house/hardwood-flooring-new-westminster-house-13.jpg", alt: "Solid hardwood flooring installed in a New Westminster home", orientation: "landscape" },
    ],
  },
  {
    slug: "quarter-sawn-solid-hardwood-vancouver",
    title: "Quarter-Sawn Solid Hardwood Flooring",
    location: "Vancouver",
    sector: "Residential",
    services: ["Hardwood"],
    summary: "Two-and-a-quarter quarter-sawn solid hardwood, site-finished.",
    description: "Traditional 2¼-inch quarter-sawn unfinished solid hardwood installed and site-finished for a classic, durable floor. Trademark Flooring installs and finishes solid hardwood throughout Vancouver.",
    coverAlt: "Two-and-a-quarter-inch quarter-sawn solid hardwood flooring",
    images: [
    { src: "/images/gallery/quarter-sawn-solid-hardwood-vancouver/quarter-sawn-solid-hardwood-vancouver-1.jpg", alt: "Two-and-a-quarter-inch quarter-sawn solid hardwood flooring", orientation: "square" },
    { src: "/images/gallery/quarter-sawn-solid-hardwood-vancouver/quarter-sawn-solid-hardwood-vancouver-2.jpg", alt: "Two-and-a-quarter-inch quarter-sawn solid hardwood flooring", orientation: "portrait" },
    { src: "/images/gallery/quarter-sawn-solid-hardwood-vancouver/quarter-sawn-solid-hardwood-vancouver-3.jpg", alt: "Two-and-a-quarter-inch quarter-sawn solid hardwood flooring", orientation: "portrait" },
    { src: "/images/gallery/quarter-sawn-solid-hardwood-vancouver/quarter-sawn-solid-hardwood-vancouver-4.jpg", alt: "Two-and-a-quarter-inch quarter-sawn solid hardwood flooring", orientation: "portrait" },
    { src: "/images/gallery/quarter-sawn-solid-hardwood-vancouver/quarter-sawn-solid-hardwood-vancouver-5.jpg", alt: "Two-and-a-quarter-inch quarter-sawn solid hardwood flooring", orientation: "portrait" },
    { src: "/images/gallery/quarter-sawn-solid-hardwood-vancouver/quarter-sawn-solid-hardwood-vancouver-6.jpg", alt: "Two-and-a-quarter-inch quarter-sawn solid hardwood flooring", orientation: "portrait" },
    { src: "/images/gallery/quarter-sawn-solid-hardwood-vancouver/quarter-sawn-solid-hardwood-vancouver-7.jpg", alt: "Two-and-a-quarter-inch quarter-sawn solid hardwood flooring", orientation: "portrait" },
    ],
  },
  {
    slug: "laminate-flooring-burnaby-brentwood-condo",
    title: "Laminate Flooring — Brentwood Condo, Burnaby",
    location: "Burnaby",
    sector: "High-Rise",
    services: ["Laminate"],
    summary: "Laminate flooring installed in a Brentwood condo in Burnaby.",
    description: "Durable laminate flooring installed in a Brentwood condo in Burnaby. Trademark Flooring installs laminate in condos and towers across Burnaby and Metro Vancouver.",
    coverAlt: "Laminate flooring installed in a Brentwood condo in Burnaby",
    images: [
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-condo/laminate-flooring-burnaby-brentwood-condo-1.jpg", alt: "Laminate flooring installed in a Brentwood condo in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-condo/laminate-flooring-burnaby-brentwood-condo-2.jpg", alt: "Laminate flooring installed in a Brentwood condo in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-condo/laminate-flooring-burnaby-brentwood-condo-3.jpg", alt: "Laminate flooring installed in a Brentwood condo in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-condo/laminate-flooring-burnaby-brentwood-condo-4.jpg", alt: "Laminate flooring installed in a Brentwood condo in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-condo/laminate-flooring-burnaby-brentwood-condo-5.jpg", alt: "Laminate flooring installed in a Brentwood condo in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-condo/laminate-flooring-burnaby-brentwood-condo-6.jpg", alt: "Laminate flooring installed in a Brentwood condo in Burnaby", orientation: "portrait" },
    ],
  },
  {
    slug: "laminate-flooring-vancouver-east-6th",
    title: "Laminate Flooring — East 6th & Clark, Vancouver",
    location: "Vancouver",
    sector: "Residential",
    services: ["Laminate"],
    summary: "Laminate flooring install near East 6th and Clark in Vancouver.",
    description: "Laminate flooring installed in a home near East 6th and Clark Drive in East Vancouver. Trademark Flooring installs laminate throughout Vancouver neighbourhoods.",
    coverAlt: "Laminate flooring installed near East 6th and Clark in Vancouver",
    images: [
    { src: "/images/gallery/laminate-flooring-vancouver-east-6th/laminate-flooring-vancouver-east-6th-1.jpg", alt: "Laminate flooring installed near East 6th and Clark in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver-east-6th/laminate-flooring-vancouver-east-6th-2.jpg", alt: "Laminate flooring installed near East 6th and Clark in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver-east-6th/laminate-flooring-vancouver-east-6th-3.jpg", alt: "Laminate flooring installed near East 6th and Clark in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver-east-6th/laminate-flooring-vancouver-east-6th-4.jpg", alt: "Laminate flooring installed near East 6th and Clark in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver-east-6th/laminate-flooring-vancouver-east-6th-5.jpg", alt: "Laminate flooring installed near East 6th and Clark in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver-east-6th/laminate-flooring-vancouver-east-6th-6.jpg", alt: "Laminate flooring installed near East 6th and Clark in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver-east-6th/laminate-flooring-vancouver-east-6th-7.jpg", alt: "Laminate flooring installed near East 6th and Clark in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver-east-6th/laminate-flooring-vancouver-east-6th-8.jpg", alt: "Laminate flooring installed near East 6th and Clark in Vancouver", orientation: "landscape" },
    ],
  },
  {
    slug: "laminate-flooring-east-vancouver-basement",
    title: "Basement Laminate Flooring — East Vancouver",
    location: "Vancouver",
    sector: "Residential",
    services: ["Laminate"],
    summary: "Basement laminate flooring installed in East Vancouver.",
    description: "Moisture-conscious laminate flooring installed in an East Vancouver basement suite. Trademark Flooring installs basement and suite laminate across Vancouver.",
    coverAlt: "Laminate flooring installed in an East Vancouver basement",
    images: [
    { src: "/images/gallery/laminate-flooring-east-vancouver-basement/laminate-flooring-east-vancouver-basement-1.jpg", alt: "Laminate flooring installed in an East Vancouver basement", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-east-vancouver-basement/laminate-flooring-east-vancouver-basement-2.jpg", alt: "Laminate flooring installed in an East Vancouver basement", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-east-vancouver-basement/laminate-flooring-east-vancouver-basement-3.jpg", alt: "Laminate flooring installed in an East Vancouver basement", orientation: "portrait" },
    ],
  },
  {
    slug: "laminate-flooring-burnaby-brentwood-tower",
    title: "Laminate Flooring — Brentwood Tower, Burnaby",
    location: "Burnaby",
    sector: "High-Rise",
    services: ["Laminate"],
    summary: "Laminate flooring installed in a Brentwood tower suite, Burnaby.",
    description: "Laminate flooring installed in a high-rise suite in Burnaby's Brentwood area. Trademark Flooring handles tower and condo laminate installs across Burnaby.",
    coverAlt: "Laminate flooring installed in a Brentwood tower suite in Burnaby",
    images: [
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-tower/laminate-flooring-burnaby-brentwood-tower-1.jpg", alt: "Laminate flooring installed in a Brentwood tower suite in Burnaby", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-tower/laminate-flooring-burnaby-brentwood-tower-2.jpg", alt: "Laminate flooring installed in a Brentwood tower suite in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-tower/laminate-flooring-burnaby-brentwood-tower-3.jpg", alt: "Laminate flooring installed in a Brentwood tower suite in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-tower/laminate-flooring-burnaby-brentwood-tower-4.jpg", alt: "Laminate flooring installed in a Brentwood tower suite in Burnaby", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-tower/laminate-flooring-burnaby-brentwood-tower-5.jpg", alt: "Laminate flooring installed in a Brentwood tower suite in Burnaby", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-tower/laminate-flooring-burnaby-brentwood-tower-6.jpg", alt: "Laminate flooring installed in a Brentwood tower suite in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-tower/laminate-flooring-burnaby-brentwood-tower-7.jpg", alt: "Laminate flooring installed in a Brentwood tower suite in Burnaby", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-burnaby-brentwood-tower/laminate-flooring-burnaby-brentwood-tower-8.jpg", alt: "Laminate flooring installed in a Brentwood tower suite in Burnaby", orientation: "portrait" },
    ],
  },
  {
    slug: "laminate-flooring-burnaby-house",
    title: "Laminate Flooring — Burnaby Home",
    location: "Burnaby",
    sector: "Residential",
    services: ["Laminate"],
    summary: "Laminate flooring installed throughout a Burnaby house.",
    description: "Hard-wearing laminate flooring installed throughout a Burnaby family home. Trademark Flooring supplies and installs laminate across Burnaby and the Lower Mainland.",
    coverAlt: "Laminate flooring installed in a Burnaby home",
    images: [
    { src: "/images/gallery/laminate-flooring-burnaby-house/laminate-flooring-burnaby-house-1.jpg", alt: "Laminate flooring installed in a Burnaby home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-house/laminate-flooring-burnaby-house-2.jpg", alt: "Laminate flooring installed in a Burnaby home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-house/laminate-flooring-burnaby-house-3.jpg", alt: "Laminate flooring installed in a Burnaby home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-house/laminate-flooring-burnaby-house-4.jpg", alt: "Laminate flooring installed in a Burnaby home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-burnaby-house/laminate-flooring-burnaby-house-5.jpg", alt: "Laminate flooring installed in a Burnaby home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-burnaby-house/laminate-flooring-burnaby-house-6.jpg", alt: "Laminate flooring installed in a Burnaby home", orientation: "portrait" },
    ],
  },
  {
    slug: "laminate-flooring-coquitlam",
    title: "Laminate Flooring — Coquitlam Home",
    location: "Coquitlam",
    sector: "Residential",
    services: ["Laminate"],
    summary: "Laminate flooring installed in a Coquitlam home.",
    description: "Durable, great-looking laminate flooring installed in a Coquitlam home. Trademark Flooring installs laminate flooring throughout Coquitlam and the Tri-Cities.",
    coverAlt: "Laminate flooring installed in a Coquitlam home",
    images: [
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-1.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-2.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-3.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-4.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-5.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-6.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-7.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-8.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-9.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-coquitlam/laminate-flooring-coquitlam-10.jpg", alt: "Laminate flooring installed in a Coquitlam home", orientation: "landscape" },
    ],
  },
  {
    slug: "laminate-flooring-downtown-vancouver",
    title: "Laminate Flooring — Downtown Vancouver",
    location: "Vancouver",
    sector: "High-Rise",
    services: ["Laminate"],
    summary: "Laminate flooring installed in a downtown Vancouver condo.",
    description: "Clean, modern laminate flooring installed in a downtown Vancouver condo. Trademark Flooring installs laminate in downtown towers and condos across Vancouver.",
    coverAlt: "Laminate flooring installed in a downtown Vancouver condo",
    images: [
    { src: "/images/gallery/laminate-flooring-downtown-vancouver/laminate-flooring-downtown-vancouver-1.jpg", alt: "Laminate flooring installed in a downtown Vancouver condo", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-downtown-vancouver/laminate-flooring-downtown-vancouver-2.jpg", alt: "Laminate flooring installed in a downtown Vancouver condo", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-downtown-vancouver/laminate-flooring-downtown-vancouver-3.jpg", alt: "Laminate flooring installed in a downtown Vancouver condo", orientation: "portrait" },
    ],
  },
  {
    slug: "laminate-flooring-mission",
    title: "Laminate Flooring — Mission, BC",
    location: "Mission",
    sector: "Residential",
    services: ["Laminate"],
    summary: "Laminate flooring installed in a Mission, BC home.",
    description: "Laminate flooring installed in a home in Mission, BC. Trademark Flooring travels across the Lower Mainland, from Vancouver out to Mission and the Fraser Valley.",
    coverAlt: "Laminate flooring installed in a Mission, BC home",
    images: [
    { src: "/images/gallery/laminate-flooring-mission/laminate-flooring-mission-1.jpg", alt: "Laminate flooring installed in a Mission, BC home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-mission/laminate-flooring-mission-2.jpg", alt: "Laminate flooring installed in a Mission, BC home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-mission/laminate-flooring-mission-3.jpg", alt: "Laminate flooring installed in a Mission, BC home", orientation: "portrait" },
    ],
  },
  {
    slug: "laminate-flooring-maple-ridge",
    title: "Laminate Flooring — Maple Ridge",
    location: "Maple Ridge",
    sector: "Residential",
    services: ["Laminate"],
    summary: "Laminate flooring installed in a Maple Ridge home.",
    description: "Laminate flooring supplied and installed in a Maple Ridge home. Trademark Flooring serves Maple Ridge, Pitt Meadows, and the wider Lower Mainland.",
    coverAlt: "Laminate flooring installed in a Maple Ridge home",
    images: [
    { src: "/images/gallery/laminate-flooring-maple-ridge/laminate-flooring-maple-ridge-1.jpg", alt: "Laminate flooring installed in a Maple Ridge home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-maple-ridge/laminate-flooring-maple-ridge-2.jpg", alt: "Laminate flooring installed in a Maple Ridge home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-maple-ridge/laminate-flooring-maple-ridge-3.jpg", alt: "Laminate flooring installed in a Maple Ridge home", orientation: "landscape" },
    ],
  },
  {
    slug: "laminate-flooring-vancouver",
    title: "Laminate Flooring — Vancouver",
    location: "Vancouver",
    sector: "Residential",
    services: ["Laminate"],
    summary: "Laminate flooring installed in a Vancouver home.",
    description: "Laminate flooring installed for a Vancouver homeowner — a budget-friendly, hard-wearing finish. Trademark Flooring installs laminate throughout Vancouver.",
    coverAlt: "Laminate flooring installed in a Vancouver home",
    images: [
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-1.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-2.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-3.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-4.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-5.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-6.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-7.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-8.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/laminate-flooring-vancouver/laminate-flooring-vancouver-9.jpg", alt: "Laminate flooring installed in a Vancouver home", orientation: "portrait" },
    ],
  },
  {
    slug: "self-levelling-vancouver-broadway-alma",
    title: "Self-Levelling — Broadway & Alma, Vancouver",
    location: "Vancouver",
    sector: "Commercial",
    services: ["Self-Levelling"],
    summary: "Self-levelling underlayment near Broadway and Alma in Vancouver.",
    description: "Self-levelling underlayment poured to create a flat, finish-ready floor near Broadway and Alma in Vancouver. Trademark Flooring provides floor levelling across Vancouver.",
    coverAlt: "Self-levelling underlayment poured near Broadway and Alma in Vancouver",
    images: [
    { src: "/images/gallery/self-levelling-vancouver-broadway-alma/self-levelling-vancouver-broadway-alma-1.jpg", alt: "Self-levelling underlayment poured near Broadway and Alma in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-broadway-alma/self-levelling-vancouver-broadway-alma-2.jpg", alt: "Self-levelling underlayment poured near Broadway and Alma in Vancouver", orientation: "portrait" },
    ],
  },
  {
    slug: "self-levelling-burnaby-brentwood-showroom",
    title: "Self-Levelling — Brentwood Showroom, Burnaby",
    location: "Burnaby",
    sector: "Commercial",
    services: ["Self-Levelling"],
    featured: true,
    summary: "Showroom floor levelling in Burnaby's Brentwood area.",
    description: "Self-levelling underlayment pumped across a Brentwood showroom floor in Burnaby to prep for finished flooring. Trademark Flooring levels commercial and retail floors across Burnaby.",
    coverAlt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby",
    images: [
    { src: "/images/gallery/self-levelling-burnaby-brentwood-showroom/self-levelling-burnaby-brentwood-showroom-1.jpg", alt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-burnaby-brentwood-showroom/self-levelling-burnaby-brentwood-showroom-2.jpg", alt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-burnaby-brentwood-showroom/self-levelling-burnaby-brentwood-showroom-3.jpg", alt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-burnaby-brentwood-showroom/self-levelling-burnaby-brentwood-showroom-4.jpg", alt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-burnaby-brentwood-showroom/self-levelling-burnaby-brentwood-showroom-5.jpg", alt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-burnaby-brentwood-showroom/self-levelling-burnaby-brentwood-showroom-6.jpg", alt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-burnaby-brentwood-showroom/self-levelling-burnaby-brentwood-showroom-7.jpg", alt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-burnaby-brentwood-showroom/self-levelling-burnaby-brentwood-showroom-8.jpg", alt: "Self-levelling underlayment across a Brentwood showroom floor in Burnaby", orientation: "portrait" },
    ],
  },
  {
    slug: "self-levelling-downtown-vancouver-condo",
    title: "Self-Levelling — Downtown Vancouver Condo",
    location: "Vancouver",
    sector: "High-Rise",
    services: ["Self-Levelling"],
    summary: "Condo floor levelling in downtown Vancouver.",
    description: "Self-levelling underlayment poured in a downtown Vancouver condo ahead of new flooring. Trademark Flooring levels condo and tower floors throughout downtown Vancouver.",
    coverAlt: "Self-levelling underlayment in a downtown Vancouver condo",
    images: [
    { src: "/images/gallery/self-levelling-downtown-vancouver-condo/self-levelling-downtown-vancouver-condo-1.jpg", alt: "Self-levelling underlayment in a downtown Vancouver condo", orientation: "landscape" },
    ],
  },
  {
    slug: "self-levelling-vancouver-davie-street",
    title: "Self-Levelling — Davie Street, Vancouver",
    location: "Vancouver",
    sector: "High-Rise",
    services: ["Self-Levelling"],
    summary: "Levelling pour on a Davie Street project in Vancouver.",
    description: "Self-levelling underlayment pumped and poured on a Davie Street project in downtown Vancouver. Trademark Flooring handles high-rise levelling pours across Vancouver.",
    coverAlt: "Self-levelling underlayment pour on a Davie Street project in Vancouver",
    images: [
    { src: "/images/gallery/self-levelling-vancouver-davie-street/self-levelling-vancouver-davie-street-1.jpg", alt: "Self-levelling underlayment pour on a Davie Street project in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-davie-street/self-levelling-vancouver-davie-street-2.jpg", alt: "Self-levelling underlayment pour on a Davie Street project in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-davie-street/self-levelling-vancouver-davie-street-3.jpg", alt: "Self-levelling underlayment pour on a Davie Street project in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-davie-street/self-levelling-vancouver-davie-street-4.jpg", alt: "Self-levelling underlayment pour on a Davie Street project in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-davie-street/self-levelling-vancouver-davie-street-5.jpg", alt: "Self-levelling underlayment pour on a Davie Street project in Vancouver", orientation: "portrait" },
    ],
  },
  {
    slug: "self-levelling-vancouver-wellness-centre",
    title: "Self-Levelling — Wellness Centre, Vancouver",
    location: "Vancouver",
    sector: "Commercial",
    services: ["Self-Levelling"],
    summary: "Floor levelling for a Vancouver wellness centre.",
    description: "Self-levelling underlayment installed to flatten the floors of a Vancouver wellness centre before finished flooring. Trademark Flooring levels commercial floors across Vancouver.",
    coverAlt: "Self-levelling underlayment in a Vancouver wellness centre",
    images: [
    { src: "/images/gallery/self-levelling-vancouver-wellness-centre/self-levelling-vancouver-wellness-centre-1.jpg", alt: "Self-levelling underlayment in a Vancouver wellness centre", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-wellness-centre/self-levelling-vancouver-wellness-centre-2.jpg", alt: "Self-levelling underlayment in a Vancouver wellness centre", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-wellness-centre/self-levelling-vancouver-wellness-centre-3.jpg", alt: "Self-levelling underlayment in a Vancouver wellness centre", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-wellness-centre/self-levelling-vancouver-wellness-centre-4.jpg", alt: "Self-levelling underlayment in a Vancouver wellness centre", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-wellness-centre/self-levelling-vancouver-wellness-centre-5.jpg", alt: "Self-levelling underlayment in a Vancouver wellness centre", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-wellness-centre/self-levelling-vancouver-wellness-centre-6.jpg", alt: "Self-levelling underlayment in a Vancouver wellness centre", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-wellness-centre/self-levelling-vancouver-wellness-centre-7.jpg", alt: "Self-levelling underlayment in a Vancouver wellness centre", orientation: "portrait" },
    ],
  },
  {
    slug: "self-levelling-delta-house",
    title: "Self-Levelling — Delta Home",
    location: "Delta",
    sector: "Residential",
    services: ["Self-Levelling"],
    summary: "Whole-floor levelling in a Delta house.",
    description: "Self-levelling underlayment poured to flatten the floors of a Delta home ahead of new flooring. Trademark Flooring provides residential floor levelling across Delta and the Lower Mainland.",
    coverAlt: "Self-levelling underlayment poured in a Delta home",
    images: [
    { src: "/images/gallery/self-levelling-delta-house/self-levelling-delta-house-1.jpg", alt: "Self-levelling underlayment poured in a Delta home", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-delta-house/self-levelling-delta-house-2.jpg", alt: "Self-levelling underlayment poured in a Delta home", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-delta-house/self-levelling-delta-house-3.jpg", alt: "Self-levelling underlayment poured in a Delta home", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-delta-house/self-levelling-delta-house-4.jpg", alt: "Self-levelling underlayment poured in a Delta home", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-delta-house/self-levelling-delta-house-5.jpg", alt: "Self-levelling underlayment poured in a Delta home", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-delta-house/self-levelling-delta-house-6.jpg", alt: "Self-levelling underlayment poured in a Delta home", orientation: "portrait" },
    ],
  },
  {
    slug: "self-levelling-vancouver-point-grey",
    title: "Self-Levelling — Point Grey / UBC, Vancouver",
    location: "Vancouver",
    sector: "Residential",
    services: ["Self-Levelling"],
    featured: true,
    summary: "Floor levelling in the Point Grey / UBC area of Vancouver.",
    description: "Self-levelling underlayment installed to bring floors dead-flat in the Point Grey / UBC area of Vancouver. Trademark Flooring levels floors throughout Vancouver's west side.",
    coverAlt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver",
    images: [
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-1.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-2.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-3.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-4.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-5.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-6.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-7.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-8.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-9.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-point-grey/self-levelling-vancouver-point-grey-10.jpg", alt: "Self-levelling underlayment in a Point Grey home near UBC in Vancouver", orientation: "landscape" },
    ],
  },
  {
    slug: "self-levelling-vancouver-oakridge",
    title: "Self-Levelling — Oakridge, Vancouver",
    location: "Vancouver",
    sector: "Residential",
    services: ["Self-Levelling"],
    summary: "Levelling pour in the Oakridge area of Vancouver.",
    description: "Self-levelling underlayment poured to create a smooth, flat base in the Oakridge area of Vancouver. Trademark Flooring provides floor levelling across Vancouver.",
    coverAlt: "Self-levelling underlayment pour in the Oakridge area of Vancouver",
    images: [
    { src: "/images/gallery/self-levelling-vancouver-oakridge/self-levelling-vancouver-oakridge-1.jpg", alt: "Self-levelling underlayment pour in the Oakridge area of Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-oakridge/self-levelling-vancouver-oakridge-2.jpg", alt: "Self-levelling underlayment pour in the Oakridge area of Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-oakridge/self-levelling-vancouver-oakridge-3.jpg", alt: "Self-levelling underlayment pour in the Oakridge area of Vancouver", orientation: "landscape" },
    ],
  },
  {
    slug: "self-levelling-burnaby-metrotown-highrise",
    title: "Self-Levelling — Metrotown High-Rise, Burnaby",
    location: "Burnaby",
    sector: "High-Rise",
    services: ["Self-Levelling"],
    summary: "High-rise levelling pour at a Metrotown project in Burnaby.",
    description: "Self-levelling underlayment pumped through a Metrotown high-rise project in Burnaby. Trademark Flooring handles tower levelling pours across Burnaby and Metro Vancouver.",
    coverAlt: "Self-levelling underlayment pour at a Metrotown high-rise in Burnaby",
    images: [
    { src: "/images/gallery/self-levelling-burnaby-metrotown-highrise/self-levelling-burnaby-metrotown-highrise-1.jpg", alt: "Self-levelling underlayment pour at a Metrotown high-rise in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-burnaby-metrotown-highrise/self-levelling-burnaby-metrotown-highrise-2.jpg", alt: "Self-levelling underlayment pour at a Metrotown high-rise in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-burnaby-metrotown-highrise/self-levelling-burnaby-metrotown-highrise-3.jpg", alt: "Self-levelling underlayment pour at a Metrotown high-rise in Burnaby", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-burnaby-metrotown-highrise/self-levelling-burnaby-metrotown-highrise-4.jpg", alt: "Self-levelling underlayment pour at a Metrotown high-rise in Burnaby", orientation: "portrait" },
    ],
  },
  {
    slug: "self-levelling-richmond-warehouse",
    title: "Self-Levelling — Richmond Warehouse",
    location: "Richmond",
    sector: "Commercial",
    services: ["Self-Levelling"],
    featured: true,
    summary: "Large-area warehouse floor levelling in Richmond.",
    description: "Self-levelling underlayment poured across a large warehouse floor in Richmond for a flat, hard-wearing surface. Trademark Flooring levels industrial and commercial floors across Richmond.",
    coverAlt: "Self-levelling underlayment poured across a Richmond warehouse floor",
    images: [
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-1.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-2.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-3.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-4.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-5.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-6.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-7.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-8.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-9.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-richmond-warehouse/self-levelling-richmond-warehouse-10.jpg", alt: "Self-levelling underlayment poured across a Richmond warehouse floor", orientation: "landscape" },
    ],
  },
  {
    slug: "self-levelling-vancouver-corridor",
    title: "Self-Levelling — Corridor Project, Vancouver",
    location: "Vancouver",
    sector: "Multi-Family",
    services: ["Self-Levelling"],
    summary: "Corridor floor levelling for a Vancouver building.",
    description: "Self-levelling underlayment poured through building corridors in Vancouver ahead of new flooring. Trademark Flooring levels multi-family corridors and common areas across Vancouver.",
    coverAlt: "Self-levelling underlayment in a building corridor in Vancouver",
    images: [
    { src: "/images/gallery/self-levelling-vancouver-corridor/self-levelling-vancouver-corridor-1.jpg", alt: "Self-levelling underlayment in a building corridor in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-corridor/self-levelling-vancouver-corridor-2.jpg", alt: "Self-levelling underlayment in a building corridor in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-vancouver-corridor/self-levelling-vancouver-corridor-3.jpg", alt: "Self-levelling underlayment in a building corridor in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-corridor/self-levelling-vancouver-corridor-4.jpg", alt: "Self-levelling underlayment in a building corridor in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-corridor/self-levelling-vancouver-corridor-5.jpg", alt: "Self-levelling underlayment in a building corridor in Vancouver", orientation: "portrait" },
    ],
  },
  {
    slug: "self-levelling-vancouver-west-broadway-highrise",
    title: "Self-Levelling — West Broadway High-Rise, Vancouver",
    location: "Vancouver",
    sector: "High-Rise",
    services: ["Self-Levelling"],
    summary: "Residential high-rise levelling pour on West Broadway, Vancouver.",
    description: "Self-levelling underlayment pumped through a residential high-rise on West Broadway in Vancouver. Trademark Flooring handles high-rise levelling across Vancouver.",
    coverAlt: "Self-levelling underlayment pour in a West Broadway high-rise in Vancouver",
    images: [
    { src: "/images/gallery/self-levelling-vancouver-west-broadway-highrise/self-levelling-vancouver-west-broadway-highrise-1.jpg", alt: "Self-levelling underlayment pour in a West Broadway high-rise in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-vancouver-west-broadway-highrise/self-levelling-vancouver-west-broadway-highrise-2.jpg", alt: "Self-levelling underlayment pour in a West Broadway high-rise in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-west-broadway-highrise/self-levelling-vancouver-west-broadway-highrise-3.jpg", alt: "Self-levelling underlayment pour in a West Broadway high-rise in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-vancouver-west-broadway-highrise/self-levelling-vancouver-west-broadway-highrise-4.jpg", alt: "Self-levelling underlayment pour in a West Broadway high-rise in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-west-broadway-highrise/self-levelling-vancouver-west-broadway-highrise-5.jpg", alt: "Self-levelling underlayment pour in a West Broadway high-rise in Vancouver", orientation: "landscape" },
    { src: "/images/gallery/self-levelling-vancouver-west-broadway-highrise/self-levelling-vancouver-west-broadway-highrise-6.jpg", alt: "Self-levelling underlayment pour in a West Broadway high-rise in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/self-levelling-vancouver-west-broadway-highrise/self-levelling-vancouver-west-broadway-highrise-7.jpg", alt: "Self-levelling underlayment pour in a West Broadway high-rise in Vancouver", orientation: "portrait" },
    ],
  },
  {
    slug: "engineered-hardwood-stairs-surrey",
    title: "Engineered Hardwood Stairs — Surrey",
    location: "Surrey",
    sector: "Residential",
    services: ["Stairs"],
    summary: "Engineered hardwood stairs built in a Surrey home.",
    description: "Engineered hardwood stair treads and risers installed for a clean, modern staircase in a Surrey home. Trademark Flooring builds and clads stairs across Surrey and the Lower Mainland.",
    coverAlt: "Engineered hardwood stairs installed in a Surrey home",
    images: [
    { src: "/images/gallery/engineered-hardwood-stairs-surrey/engineered-hardwood-stairs-surrey-1.jpg", alt: "Engineered hardwood stairs installed in a Surrey home", orientation: "portrait" },
    { src: "/images/gallery/engineered-hardwood-stairs-surrey/engineered-hardwood-stairs-surrey-2.jpg", alt: "Engineered hardwood stairs installed in a Surrey home", orientation: "portrait" },
    { src: "/images/gallery/engineered-hardwood-stairs-surrey/engineered-hardwood-stairs-surrey-3.jpg", alt: "Engineered hardwood stairs installed in a Surrey home", orientation: "portrait" },
    ],
  },
  {
    slug: "solid-wood-stairs-vancouver-kitsilano",
    title: "Solid Wood Stairs — Kitsilano, Vancouver",
    location: "Vancouver",
    sector: "Residential",
    services: ["Stairs"],
    summary: "Solid fir wood stairs for a Kitsilano home in Vancouver.",
    description: "Solid fir wood stairs built for a Kitsilano home near Broadway in Vancouver. Trademark Flooring crafts solid and clad wood staircases throughout Vancouver.",
    coverAlt: "Solid fir wood stairs in a Kitsilano home in Vancouver",
    images: [
    { src: "/images/gallery/solid-wood-stairs-vancouver-kitsilano/solid-wood-stairs-vancouver-kitsilano-1.jpg", alt: "Solid fir wood stairs in a Kitsilano home in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/solid-wood-stairs-vancouver-kitsilano/solid-wood-stairs-vancouver-kitsilano-2.jpg", alt: "Solid fir wood stairs in a Kitsilano home in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/solid-wood-stairs-vancouver-kitsilano/solid-wood-stairs-vancouver-kitsilano-3.jpg", alt: "Solid fir wood stairs in a Kitsilano home in Vancouver", orientation: "portrait" },
    ],
  },
  {
    slug: "hardwood-stairs-west-vancouver",
    title: "Hardwood Stairs — West Vancouver",
    location: "West Vancouver",
    sector: "Residential",
    services: ["Stairs"],
    featured: true,
    summary: "Hardwood staircase built in a West Vancouver home.",
    description: "Hardwood stair treads and risers installed for an elegant staircase in a West Vancouver home. Trademark Flooring builds premium hardwood stairs across the North Shore and Lower Mainland.",
    coverAlt: "Hardwood stairs installed in a West Vancouver home",
    images: [
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-1.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-2.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-3.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-4.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-5.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-6.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-7.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-8.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-9.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-10.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-11.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-12.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-west-vancouver/hardwood-stairs-west-vancouver-13.jpg", alt: "Hardwood stairs installed in a West Vancouver home", orientation: "portrait" },
    ],
  },
  {
    slug: "hardwood-stairs-vancouver",
    title: "Hardwood Stairs — Vancouver",
    location: "Vancouver",
    sector: "Residential",
    services: ["Stairs"],
    summary: "Hardwood staircase installed in a Vancouver home.",
    description: "Hardwood stairs installed to match a home's flooring in Vancouver. Trademark Flooring builds and refinishes hardwood staircases throughout Vancouver.",
    coverAlt: "Hardwood stairs installed in a Vancouver home",
    images: [
    { src: "/images/gallery/hardwood-stairs-vancouver/hardwood-stairs-vancouver-1.jpg", alt: "Hardwood stairs installed in a Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/hardwood-stairs-vancouver/hardwood-stairs-vancouver-2.jpg", alt: "Hardwood stairs installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-vancouver/hardwood-stairs-vancouver-3.jpg", alt: "Hardwood stairs installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-vancouver/hardwood-stairs-vancouver-4.jpg", alt: "Hardwood stairs installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-vancouver/hardwood-stairs-vancouver-5.jpg", alt: "Hardwood stairs installed in a Vancouver home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-vancouver/hardwood-stairs-vancouver-6.jpg", alt: "Hardwood stairs installed in a Vancouver home", orientation: "landscape" },
    { src: "/images/gallery/hardwood-stairs-vancouver/hardwood-stairs-vancouver-7.jpg", alt: "Hardwood stairs installed in a Vancouver home", orientation: "portrait" },
    ],
  },
  {
    slug: "hardwood-stairs-vancouver-kitsilano",
    title: "Hardwood Stairs — Kitsilano, Vancouver",
    location: "Vancouver",
    sector: "Residential",
    services: ["Stairs"],
    summary: "Hardwood staircase built for a Kitsilano home in Vancouver.",
    description: "Hardwood stairs installed for a Kitsilano home in Vancouver's west side. Trademark Flooring builds hardwood staircases across Vancouver neighbourhoods.",
    coverAlt: "Hardwood stairs installed in a Kitsilano home in Vancouver",
    images: [
    { src: "/images/gallery/hardwood-stairs-vancouver-kitsilano/hardwood-stairs-vancouver-kitsilano-1.jpg", alt: "Hardwood stairs installed in a Kitsilano home in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-vancouver-kitsilano/hardwood-stairs-vancouver-kitsilano-2.jpg", alt: "Hardwood stairs installed in a Kitsilano home in Vancouver", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-vancouver-kitsilano/hardwood-stairs-vancouver-kitsilano-3.jpg", alt: "Hardwood stairs installed in a Kitsilano home in Vancouver", orientation: "portrait" },
    ],
  },
  {
    slug: "laminate-stairs-mission",
    title: "Laminate Stairs — Mission, BC",
    location: "Mission",
    sector: "Residential",
    services: ["Stairs"],
    summary: "Laminate-clad stairs built in a Mission, BC home.",
    description: "Laminate stair treads and risers installed to match the floors of a Mission, BC home. Trademark Flooring builds laminate and hardwood stairs across the Fraser Valley and Lower Mainland.",
    coverAlt: "Laminate-clad stairs installed in a Mission, BC home",
    images: [
    { src: "/images/gallery/laminate-stairs-mission/laminate-stairs-mission-1.jpg", alt: "Laminate-clad stairs installed in a Mission, BC home", orientation: "landscape" },
    { src: "/images/gallery/laminate-stairs-mission/laminate-stairs-mission-2.jpg", alt: "Laminate-clad stairs installed in a Mission, BC home", orientation: "portrait" },
    { src: "/images/gallery/laminate-stairs-mission/laminate-stairs-mission-3.jpg", alt: "Laminate-clad stairs installed in a Mission, BC home", orientation: "portrait" },
    { src: "/images/gallery/laminate-stairs-mission/laminate-stairs-mission-4.jpg", alt: "Laminate-clad stairs installed in a Mission, BC home", orientation: "portrait" },
    ],
  },
  {
    slug: "hardwood-stairs-port-coquitlam",
    title: "Hardwood Stairs — Port Coquitlam",
    location: "Port Coquitlam",
    sector: "Residential",
    services: ["Stairs"],
    summary: "Hardwood staircase installed in a Port Coquitlam home.",
    description: "Hardwood stairs built and installed in a Port Coquitlam home. Trademark Flooring builds hardwood staircases across the Tri-Cities and Lower Mainland.",
    coverAlt: "Hardwood stairs installed in a Port Coquitlam home",
    images: [
    { src: "/images/gallery/hardwood-stairs-port-coquitlam/hardwood-stairs-port-coquitlam-1.jpg", alt: "Hardwood stairs installed in a Port Coquitlam home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-port-coquitlam/hardwood-stairs-port-coquitlam-2.jpg", alt: "Hardwood stairs installed in a Port Coquitlam home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-port-coquitlam/hardwood-stairs-port-coquitlam-3.jpg", alt: "Hardwood stairs installed in a Port Coquitlam home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-port-coquitlam/hardwood-stairs-port-coquitlam-4.jpg", alt: "Hardwood stairs installed in a Port Coquitlam home", orientation: "portrait" },
    { src: "/images/gallery/hardwood-stairs-port-coquitlam/hardwood-stairs-port-coquitlam-5.jpg", alt: "Hardwood stairs installed in a Port Coquitlam home", orientation: "portrait" },
    ],
  },
  {
    slug: "vinyl-stairs-new-westminster",
    title: "Vinyl Stairs — New Westminster",
    location: "New Westminster",
    sector: "Residential",
    services: ["Stairs"],
    summary: "Vinyl-clad stairs built in a New Westminster home.",
    description: "Vinyl plank stair treads and risers installed for a durable, water-resistant staircase in a New Westminster home. Trademark Flooring builds vinyl and hardwood stairs across the Lower Mainland.",
    coverAlt: "Vinyl-clad stairs installed in a New Westminster home",
    images: [
    { src: "/images/gallery/vinyl-stairs-new-westminster/vinyl-stairs-new-westminster-1.jpg", alt: "Vinyl-clad stairs installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/vinyl-stairs-new-westminster/vinyl-stairs-new-westminster-2.jpg", alt: "Vinyl-clad stairs installed in a New Westminster home", orientation: "landscape" },
    { src: "/images/gallery/vinyl-stairs-new-westminster/vinyl-stairs-new-westminster-3.jpg", alt: "Vinyl-clad stairs installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/vinyl-stairs-new-westminster/vinyl-stairs-new-westminster-4.jpg", alt: "Vinyl-clad stairs installed in a New Westminster home", orientation: "landscape" },
    { src: "/images/gallery/vinyl-stairs-new-westminster/vinyl-stairs-new-westminster-5.jpg", alt: "Vinyl-clad stairs installed in a New Westminster home", orientation: "portrait" },
    { src: "/images/gallery/vinyl-stairs-new-westminster/vinyl-stairs-new-westminster-6.jpg", alt: "Vinyl-clad stairs installed in a New Westminster home", orientation: "portrait" },
    ],
  },
  {
    slug: "designer-vinyl-flooring-burnaby",
    title: "Designer Vinyl Flooring — Burnaby",
    location: "Burnaby",
    sector: "Residential",
    services: ["Vinyl"],
    summary: "Designer luxury vinyl plank installed in a Burnaby home.",
    description: "Designer luxury vinyl plank installed for a stylish, water-resistant floor in a Burnaby home. Trademark Flooring supplies and installs luxury vinyl across Burnaby and Metro Vancouver.",
    coverAlt: "Designer luxury vinyl plank flooring installed in a Burnaby home",
    images: [
    { src: "/images/gallery/designer-vinyl-flooring-burnaby/designer-vinyl-flooring-burnaby-1.jpg", alt: "Designer luxury vinyl plank flooring installed in a Burnaby home", orientation: "landscape" },
    { src: "/images/gallery/designer-vinyl-flooring-burnaby/designer-vinyl-flooring-burnaby-2.jpg", alt: "Designer luxury vinyl plank flooring installed in a Burnaby home", orientation: "landscape" },
    { src: "/images/gallery/designer-vinyl-flooring-burnaby/designer-vinyl-flooring-burnaby-3.jpg", alt: "Designer luxury vinyl plank flooring installed in a Burnaby home", orientation: "portrait" },
    { src: "/images/gallery/designer-vinyl-flooring-burnaby/designer-vinyl-flooring-burnaby-4.jpg", alt: "Designer luxury vinyl plank flooring installed in a Burnaby home", orientation: "portrait" },
    { src: "/images/gallery/designer-vinyl-flooring-burnaby/designer-vinyl-flooring-burnaby-5.jpg", alt: "Designer luxury vinyl plank flooring installed in a Burnaby home", orientation: "portrait" },
    ],
  },
  {
    slug: "vinyl-flooring-vancouver-office",
    title: "Vinyl Flooring — Vancouver Office",
    location: "Vancouver",
    sector: "Commercial",
    services: ["Vinyl"],
    featured: true,
    summary: "Commercial vinyl flooring installed in a Vancouver office.",
    description: "Hard-wearing commercial vinyl flooring installed throughout a Vancouver office. Trademark Flooring installs luxury vinyl and commercial resilient flooring across Vancouver.",
    coverAlt: "Commercial vinyl flooring installed in a Vancouver office",
    images: [
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-1.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-2.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-3.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-4.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-5.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-6.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-7.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-8.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-9.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-10.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-11.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-12.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-13.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-14.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-15.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-16.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    { src: "/images/gallery/vinyl-flooring-vancouver-office/vinyl-flooring-vancouver-office-17.jpg", alt: "Commercial vinyl flooring installed in a Vancouver office", orientation: "portrait" },
    ],
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

/** Sorted list of the cities represented in the gallery. */
export function galleryCities(): string[] {
  return Array.from(new Set(projects.map((p) => p.location))).sort();
}

/** Total image count across all projects. */
export function totalImageCount(): number {
  return projects.reduce((sum, p) => sum + p.images.length, 0);
}
